const bilingual = (en, hi) => ({ en, hi });

export const intents = [
  {
    id: 'services',
    strong: ['services', 'service', 'web development', 'website development', 'web application', 'mern', 'react development'],
    weak: ['website', 'websites', 'build', 'offer', 'provide'],
    phrases: ['what services do you offer', 'what do you offer', 'what can you build', 'do you build websites'],
    exact: [],
    answer: bilingual('TechSlot’s services listed on the website include:', 'Website par listed TechSlot ki services hain:'),
    more: bilingual('Here are the services currently listed on the website:', 'Website par filhaal listed services yeh hain:'),
    later: bilingual('Those are the services currently published by TechSlot.', 'TechSlot ki website par filhaal yehi services listed hain.'),
    ask: bilingual('Which service would you like to know about?', 'Aap kis service ke baare mein jaanna chahenge?'),
    related: ['portfolio', 'process', 'pricing'],
    links: [{ label: bilingual('View services', 'Services dekhein'), url: '/services' }],
    dynamic: 'services',
  },
  {
    id: 'portfolio',
    strong: ['portfolio', 'projects', 'work samples', 'case studies'],
    weak: ['project', 'example', 'show', 'see'],
    phrases: ['can i see your portfolio', 'show me your work', 'view your projects', 'past projects', 'your portfolio'],
    exact: [],
    answer: bilingual('Here are some projects published on the website:', 'Website par publish kiye gaye kuch projects yeh hain:'),
    more: bilingual('More details about the published projects:', 'Published projects ki aur details:'),
    later: bilingual('You can browse the project portfolio on the website.', 'Aap website par project portfolio dekh sakte hain.'),
    ask: bilingual('Would you like to see the services too?', 'Kya aap services bhi dekhna chahenge?'),
    related: ['services', 'process', 'technology'],
    links: [{ label: bilingual('View portfolio', 'Portfolio dekhein'), url: '/projects' }],
    dynamic: 'portfolio',
  },
  {
    id: 'pricing',
    strong: ['pricing', 'price', 'prices', 'cost', 'charge', 'quote', 'budget'],
    weak: ['much', 'expensive', 'paisa', 'kitna', 'kitne', 'ka'],
    phrases: ['how much for', 'how much does it cost', 'what does a website cost', 'price for a website', 'website kitne ka', 'kitna paisa lagega', 'kitne ka banega', 'what are your prices', 'how much do you charge'],
    exact: [],
    answer: bilingual('The website does not publish fixed prices. The contact form provides these budget options; they are not a quote:', 'Website par fixed prices publish nahi hain. Contact form mein yeh budget options hain; yeh quote nahi hain:'),
    more: bilingual('There is no published price list. The available form budget ranges are:', 'Koi published price list nahi hai. Form mein available budget ranges hain:'),
    later: bilingual('Pricing is not published; a quote depends on your project. You can share details using the contact form.', 'Pricing publish nahi hai; quote project par depend karega. Aap contact form se details bhej sakte hain.'),
    ask: bilingual('Would you like to send your project inquiry from this chat?', 'Kya aap chat se apni project inquiry bhejna chahenge?'),
    related: ['timeline', 'start', 'services'],
    links: [{ label: bilingual('Contact TechSlot', 'TechSlot se contact karein'), url: '/contact' }],
    dynamic: 'budgets',
    offerLead: true,
  },
  {
    id: 'timeline',
    strong: ['timeline', 'duration', 'deadline', 'delivery', 'weeks', 'months'],
    weak: ['long', 'take', 'days', 'din', 'kab', 'kitne'],
    phrases: ['how long does a project take', 'how long for delivery', 'what is the timeline', 'how long will it take', 'kitne din me ho jayega', 'kitne din lagenge', 'how many days'],
    exact: [],
    answer: bilingual('The form lists these timeline preferences. They are not delivery guarantees; timing depends on the project scope:', 'Form mein yeh timeline preferences hain. Yeh delivery guarantee nahi hain; duration project ke scope par depend karega:'),
    more: bilingual('The published form timeline options are:', 'Form par listed timeline options hain:'),
    later: bilingual('A delivery estimate depends on project requirements; these are only the form choices.', 'Delivery estimate project requirements par depend karta hai; yeh sirf form ke options hain.'),
    ask: bilingual('Would you like to send your project inquiry from this chat?', 'Kya aap chat se apni project inquiry bhejna chahenge?'),
    related: ['pricing', 'process', 'start'],
    links: [{ label: bilingual('Contact TechSlot', 'TechSlot se contact karein'), url: '/contact' }],
    dynamic: 'timelines',
    offerLead: true,
  },
  {
    id: 'process',
    strong: ['process', 'workflow', 'steps', 'discovery', 'planning', 'testing', 'deployment'],
    weak: ['work', 'approach'],
    phrases: ['how does the project process work', 'how do projects work', 'how do you work', 'project steps'],
    exact: [],
    answer: bilingual('The website describes a six-step process: discovery, planning, development, testing, deployment, and post-launch support.', 'Website par chhe steps ka process diya hai: discovery, planning, development, testing, deployment, aur launch ke baad support.'),
    more: bilingual('The published process moves through discovery, planning, development, testing, deployment, and post-launch support.', 'Published process mein discovery, planning, development, testing, deployment, aur launch ke baad support shamil hain.'),
    later: bilingual('The six published stages are discovery, planning, development, testing, deployment, and post-launch support.', 'Published chhe stages hain: discovery, planning, development, testing, deployment, aur launch ke baad support.'),
    ask: bilingual('Would you like to discuss a project?', 'Kya aap kisi project par baat karna chahenge?'),
    related: ['services', 'timeline', 'start'],
    links: [],
  },
  {
    id: 'technology',
    strong: ['technology', 'technologies', 'stack', 'react', 'nodejs', 'express', 'mongodb', 'javascript', 'typescript'],
    weak: ['tech', 'tools', 'use'],
    phrases: ['what technologies do you use', 'which technologies', 'your tech stack', 'what tech do you use'],
    exact: [],
    answer: bilingual('Technologies named on the website include React, Node.js, Express, MongoDB, JavaScript, TypeScript, JWT, REST APIs, Vite, Mongoose, Redis, AWS, Docker, Socket.io, and GraphQL. The stack depends on the project.', 'Website par React, Node.js, Express, MongoDB, JavaScript, TypeScript, JWT, REST APIs, Vite, Mongoose, Redis, AWS, Docker, Socket.io, aur GraphQL ka zikr hai. Stack project par depend karta hai.'),
    more: bilingual('The website names React, Node.js, Express, MongoDB, JavaScript, TypeScript, JWT, REST APIs, Vite, Mongoose, Redis, AWS, Docker, Socket.io, and GraphQL; the project determines the stack.', 'Website par React, Node.js, Express, MongoDB, JavaScript, TypeScript, JWT, REST APIs, Vite, Mongoose, Redis, AWS, Docker, Socket.io, aur GraphQL listed hain; stack project ke hisaab se chuna jaata hai.'),
    later: bilingual('The published stack includes React, Node.js, Express, MongoDB, JavaScript, TypeScript, and other tools listed on the website.', 'Published stack mein React, Node.js, Express, MongoDB, JavaScript, TypeScript, aur website par listed doosre tools hain.'),
    ask: bilingual('Would you like to see the published services?', 'Kya aap published services dekhna chahenge?'),
    related: ['services', 'portfolio', 'process'],
    links: [],
  },
  {
    id: 'maintenance',
    strong: ['maintenance', 'support', 'updates', 'postlaunch'],
    weak: ['after', 'launch'],
    phrases: ['do you offer maintenance', 'post launch support', 'ongoing support', 'website maintenance'],
    exact: [],
    answer: bilingual('The website mentions post-launch maintenance, updates, and technical support. Specific plans or rates are not published.', 'Website par launch ke baad maintenance, updates, aur technical support ka zikr hai. Specific plans ya rates publish nahi hain.'),
    more: bilingual('Ongoing maintenance and technical support are mentioned, but specific plans and rates are not published.', 'Ongoing maintenance aur technical support ka zikr hai, lekin specific plans aur rates publish nahi hain.'),
    later: bilingual('The website does not publish specific maintenance plans or rates.', 'Website par specific maintenance plans ya rates publish nahi hain.'),
    ask: bilingual('Would you like to discuss your requirements?', 'Kya aap apni requirements par baat karna chahenge?'),
    related: ['services', 'start', 'pricing'],
    links: [],
  },
  {
    id: 'start',
    strong: ['contact', 'inquiry', 'enquiry', 'start', 'started', 'getintouch'],
    weak: ['form', 'project', 'begin'],
    phrases: ['how can i start a project', 'how do i get started', 'how do i contact you', 'start a project', 'get in touch', 'project kaise shuru karoon'],
    exact: [],
    answer: bilingual('You can submit your project details using the contact form, or send an inquiry directly in this chat.', 'Aap contact form se project details bhej sakte hain, ya isi chat mein inquiry submit kar sakte hain.'),
    more: bilingual('To start, share your name, email, project type, budget, timeline, and a short project overview using the contact form or this chat.', 'Shuru karne ke liye contact form ya is chat par apna naam, email, project type, budget, timeline, aur project ka short overview bhejein.'),
    later: bilingual('You can use the contact form or send your inquiry here in the chat.', 'Aap contact form use kar sakte hain ya isi chat mein inquiry bhej sakte hain.'),
    ask: bilingual('Would you like to send your inquiry from this chat?', 'Kya aap chat se apni inquiry bhejna chahenge?'),
    related: ['pricing', 'timeline', 'services'],
    links: [{ label: bilingual('Open contact form', 'Contact form kholein'), url: '/contact' }],
    offerLead: true,
  },
  {
    id: 'notOffered',
    strong: ['seo', 'mobile app', 'mobile apps', 'android app', 'ios app'],
    weak: [],
    phrases: ['do you do seo', 'do you build mobile apps', 'do you make mobile apps'],
    exact: ['seo'],
    answer: bilingual('That service is not listed among the services published on the website. Please use /contact if you want to ask about a specific requirement.', 'Yeh service website par listed services mein nahi hai. Kisi specific requirement ke baare mein poochne ke liye /contact par message bhejein.'),
    more: bilingual('I can only confirm the services published on the website; that service is not listed there.', 'Main website par published services hi confirm kar sakta hoon; yeh service wahan listed nahi hai.'),
    later: bilingual('That service is not listed on the website.', 'Yeh service website par listed nahi hai.'),
    ask: bilingual('Would you like to see the services that are listed?', 'Kya aap listed services dekhna chahenge?'),
    related: ['services', 'start'],
    links: [{ label: bilingual('Contact TechSlot', 'TechSlot se contact karein'), url: '/contact' }],
  },
  {
    id: 'greeting',
    strong: ['hello', 'hi', 'hey', 'namaste', 'salaam'],
    weak: [],
    phrases: ['good morning', 'good afternoon', 'good evening'],
    exact: ['hi', 'hello', 'hey', 'namaste', 'salaam'],
    answer: bilingual('Hi! What would you like to know about TechSlot?', 'Namaste! Aap TechSlot ke baare mein kya jaanna chahenge?'),
    more: bilingual('Hello again! Ask me about services, projects, pricing, or timelines.', 'Namaste! Services, projects, pricing, ya timeline ke baare mein poochhein.'),
    later: bilingual('I’m here if you have another question.', 'Aapka koi aur sawaal ho toh poochhein.'),
    ask: bilingual('What can I help you with?', 'Main aapki kis baat mein madad karoon?'),
    related: ['services', 'portfolio', 'pricing'],
    links: [],
  },
  {
    id: 'thanks',
    strong: ['thanks', 'thankyou', 'shukriya', 'dhanyavaad'],
    weak: ['thank'],
    phrases: ['thank you', 'thanks a lot', 'that helps'],
    exact: ['thanks', 'thank you', 'thanks a lot', 'shukriya'],
    answer: bilingual('You’re welcome! Let me know if you have another question.', 'Aapka swagat hai! Koi aur sawaal ho toh batayein.'),
    more: bilingual('Glad I could help!', 'Madad karke khushi hui!'),
    later: bilingual('You’re welcome!', 'Aapka swagat hai!'),
    ask: bilingual('Is there anything else you’d like to know?', 'Kya aap kuch aur jaanna chahenge?'),
    related: ['services', 'portfolio', 'start'],
    links: [],
  },
  {
    id: 'bye',
    strong: ['bye', 'goodbye', 'alvida', 'khuda'],
    weak: [],
    phrases: ['see you', 'talk later'],
    exact: ['bye', 'goodbye', 'alvida'],
    answer: bilingual('Goodbye! Thanks for visiting TechSlot.', 'Alvida! TechSlot par aane ke liye shukriya.'),
    more: bilingual('Take care, and thanks for visiting TechSlot.', 'Apna khayal rakhein, TechSlot par aane ke liye shukriya.'),
    later: bilingual('Goodbye!', 'Alvida!'),
    ask: bilingual('You can come back any time.', 'Aap kabhi bhi wapas aa sakte hain.'),
    related: ['services', 'portfolio', 'start'],
    links: [],
  },
  {
    id: 'bot',
    strong: ['bot', 'robot', 'human', 'person'],
    weak: [],
    phrases: ['are you a bot', 'are you a robot', 'are you human'],
    exact: [],
    answer: bilingual('I’m TechSlot’s automated chatbot. I answer using information published on the website.', 'Main TechSlot ka automated chatbot hoon. Main website par published jaankari ke basis par jawab deta hoon.'),
    more: bilingual('I’m an automated assistant, not a person; I can help with published TechSlot information.', 'Main automated assistant hoon, insaan nahi; TechSlot ki published jaankari mein madad kar sakta hoon.'),
    later: bilingual('I’m an automated TechSlot assistant.', 'Main TechSlot ka automated assistant hoon.'),
    ask: bilingual('What would you like to ask?', 'Aap kya poochna chahenge?'),
    related: ['services', 'portfolio', 'help'],
    links: [],
  },
  {
    id: 'help',
    strong: ['help', 'assist', 'options'],
    weak: [],
    phrases: ['what can you help with', 'what can i ask', 'help me'],
    exact: ['help'],
    answer: bilingual('Ask about TechSlot’s services, portfolio, project process, technology, pricing, timelines, or how to start.', 'TechSlot ki services, portfolio, process, technology, pricing, timeline, ya shuru karne ke tareeqe ke baare mein poochhein.'),
    more: bilingual('I can answer questions about services, published projects, process, technologies, budget choices, timelines, and project inquiries.', 'Main services, published projects, process, technologies, budget options, timelines, aur project inquiries ke baare mein bata sakta hoon.'),
    later: bilingual('Try asking about services, projects, pricing, timelines, or starting a project.', 'Services, projects, pricing, timeline, ya project shuru karne ke baare mein poochhein.'),
    ask: bilingual('What would you like to know?', 'Aap kya jaanna chahenge?'),
    related: ['services', 'portfolio', 'pricing'],
    links: [],
  },
  {
    id: 'more',
    strong: ['more', 'aur', 'details'],
    weak: ['tell', 'batao', 'explain'],
    phrases: ['tell me more', 'more details', 'aur batao', 'thoda aur batao'],
    exact: ['more', 'tell me more', 'aur batao'],
    answer: bilingual('Here is a little more detail:', 'Thodi aur jaankari:'),
    more: bilingual('Here is more detail:', 'Aur jaankari:'),
    later: bilingual('I’ve shared the available details on this topic.', 'Is topic par available jaankari share kar di hai.'),
    ask: bilingual('What else would you like to know?', 'Aap aur kya jaanna chahenge?'),
    related: [],
    links: [],
  },
];

export const getIntent = (id) => intents.find((intent) => intent.id === id);
